
USE [bmnpad01]  
GO  
CREATE CLUSTERED INDEX [IX_ID_COTIZACION] ON [dbo].[PLAZOS_COT]  ([ID_COTIZACION] ASC)  
GO  
CREATE NONCLUSTERED INDEX [IX_VALOR_PLAZO] ON [dbo].[PLAZOS_COT] ([VALOR_PLAZO])   
GO 
exec sp_helpindex '[PLAZOS_COT]'